.TH PYSDM 8
.SH NAME
pysdm \- PyGTK Storage Device Manager
.SH SYNOPSIS
.B pysdm
.br
.SH DESCRIPTION
PySDM is a Storage Device Manager that allows full customization of hard disk mountpoints without manually access to fstab.
.SH SEE ALSO
.BR mount (8),
.BR umount (8),
.BR fstab(5).
.br
.SH AUTHOR
pysdm was written by Jaime Soriano Pastor
.PP
This manual page was written by Jaime Soriano Pastor <kronoss@kronoss.org>,
for the Ubuntu project (but may be used by others).
